In [1]:
import pandas as pd
# import sklearn as skl
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import svm

In [2]:
# Loading iris dataset
iris = datasets.load_iris()

In [3]:
# classes of this dataset
classes = ['Iris Setosa', 'Iris Versicolour', 'Iris Virginica']

In [4]:
# attaching variables
x = iris.data
y = iris.target

In [5]:
print("Data: ", x)
print()
print("Target: ", y)

Data:  [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9

In [6]:
# Spliting the variables for train and test.
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(120, 4)
(30, 4)
(120,)
(30,)


In [7]:
# Creating a model
model = svm.SVC()

print(model)

SVC()


In [8]:
# Training the model
model.fit(x_train, y_train)

SVC()

In [9]:
prediction = model.predict(x_test)


print(prediction)

[0 0 0 0 1 1 0 0 2 1 0 2 1 1 0 0 2 0 0 2 1 0 2 2 1 1 1 2 1 0]


In [10]:
acc = accuracy_score(y_test, prediction)

print(acc)

0.9666666666666667


In [11]:
for i, p in enumerate(prediction):
    print(classes[prediction[i]])

Iris Setosa
Iris Setosa
Iris Setosa
Iris Setosa
Iris Versicolour
Iris Versicolour
Iris Setosa
Iris Setosa
Iris Virginica
Iris Versicolour
Iris Setosa
Iris Virginica
Iris Versicolour
Iris Versicolour
Iris Setosa
Iris Setosa
Iris Virginica
Iris Setosa
Iris Setosa
Iris Virginica
Iris Versicolour
Iris Setosa
Iris Virginica
Iris Virginica
Iris Versicolour
Iris Versicolour
Iris Versicolour
Iris Virginica
Iris Versicolour
Iris Setosa


In [33]:
help(skl)

Help on package sklearn:

NAME
    sklearn

DESCRIPTION
    Machine learning module for Python
    
    sklearn is a Python module integrating classical machine
    learning algorithms in the tightly-knit world of scientific Python
    packages (numpy, scipy, matplotlib).
    
    It aims to provide simple and efficient solutions to learning problems
    that are accessible to everybody and reusable in various contexts:
    machine-learning as a versatile tool for science and engineering.
    
    See http://scikit-learn.org for complete documentation.

PACKAGE CONTENTS
    __check_build (package)
    _build_utils (package)
    _config
    _distributor_init
    _isotonic
    _loss (package)
    _min_dependencies
    base
    calibration
    cluster (package)
    compose (package)
    conftest
    covariance (package)
    cross_decomposition (package)
    datasets (package)
    decomposition (package)
    discriminant_analysis
    dummy
    ensemble (package)
    exceptions
    experime